import { execFileSync } from "node:child_process";
import pc from "picocolors";
import type { AnalysisResult, CheckRun, DiffResult } from "./types.js";

/**
 * Generate a markdown comment body from analysis results.
 */
export function generateCommentMarkdown(
  checkRun: CheckRun,
  diffUrls?: Map<string, string>
): string {
  const { summary, analysisResults, prefilterResults } = checkRun;
  const regressions = collectByType(analysisResults, "REGRESSION");
  const intentional = collectByType(analysisResults, "INTENTIONAL");
  const noise = collectByType(analysisResults, "NOISE");

  const lines: string[] = [];

  // Header
  lines.push("## 🔍 DojoWatch Visual Regression Report");
  lines.push("");
  lines.push(
    `**Branch**: \`${checkRun.branch}\` | **Commit**: \`${checkRun.commitSha.slice(0, 7)}\` | **Scope**: ${checkRun.scope}`
  );
  lines.push("");

  // Summary table
  lines.push("### Summary");
  lines.push("");
  lines.push("| Metric | Count |");
  lines.push("|--------|------:|");
  lines.push(`| Total screenshots | ${summary.total} |`);
  lines.push(`| Unchanged (SKIP) | ${summary.skipped} |`);
  lines.push(`| Analyzed | ${summary.analyzed} |`);
  lines.push(`| **Regressions** | **${summary.regressions}** |`);
  lines.push(`| Intentional | ${summary.intentional} |`);
  lines.push(`| Noise | ${summary.noise} |`);
  lines.push("");

  // Regressions
  if (regressions.length > 0) {
    lines.push("### ❌ Regressions");
    lines.push("");
    lines.push("| Severity | Element | Description | Suggested Fix |");
    lines.push("|----------|---------|-------------|---------------|");
    for (const { screenshot, diff, name } of regressions) {
      const sev =
        diff.severity === "high"
          ? "🔴 high"
          : diff.severity === "medium"
            ? "🟡 medium"
            : "🟢 low";
      const diffUrl = diffUrls?.get(name);
      const thumbnailCol = diffUrl ? ` [![diff](${diffUrl})](${diffUrl})` : "";
      lines.push(
        `| ${sev} | ${screenshot}: ${diff.element}${thumbnailCol} | ${diff.description} | ${diff.suggested_fix ?? "—"} |`
      );
    }
    lines.push("");
  } else {
    lines.push("### ✅ No regressions detected");
    lines.push("");
  }

  // Intentional changes (collapsed)
  if (intentional.length > 0) {
    lines.push("<details>");
    lines.push(`<summary>📝 Intentional changes (${intentional.length})</summary>`);
    lines.push("");
    for (const { screenshot, diff } of intentional) {
      lines.push(`- **${screenshot}**: ${diff.element} — ${diff.description}`);
    }
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  // Noise (collapsed)
  if (noise.length > 0) {
    lines.push("<details>");
    lines.push(`<summary>🔇 Noise filtered (${noise.length})</summary>`);
    lines.push("");
    for (const { screenshot, diff } of noise) {
      lines.push(`- **${screenshot}**: ${diff.element} — ${diff.description}`);
    }
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  // Pre-filter breakdown (collapsed)
  lines.push("<details>");
  lines.push("<summary>📊 Pre-filter breakdown</summary>");
  lines.push("");
  lines.push("| Screenshot | Tier | Diff pixels | % |");
  lines.push("|------------|------|------------|---|");
  for (const pf of prefilterResults) {
    lines.push(
      `| ${pf.name} (${pf.viewport}) | ${pf.tier} | ${pf.pixelDiffCount} | ${pf.pixelDiffPercent}% |`
    );
  }
  lines.push("");
  lines.push("</details>");
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("*Generated by [DojoWatch](https://github.com/DojoCodingLabs/dojowatch)*");

  return lines.join("\n");
}

/**
 * Collect all diffs of a given type across all analysis results.
 */
function collectByType(
  results: AnalysisResult[],
  type: DiffResult["type"]
): Array<{ screenshot: string; name: string; diff: DiffResult }> {
  const collected: Array<{ screenshot: string; name: string; diff: DiffResult }> = [];

  for (const result of results) {
    for (const diff of result.diffs) {
      if (diff.type === type) {
        collected.push({
          screenshot: `${result.name} (${result.viewport})`,
          name: result.name,
          diff,
        });
      }
    }
  }

  // Sort regressions by severity: high first
  if (type === "REGRESSION") {
    const order = { high: 0, medium: 1, low: 2 };
    collected.sort(
      (a, b) =>
        (order[a.diff.severity ?? "low"] ?? 3) -
        (order[b.diff.severity ?? "low"] ?? 3)
    );
  }

  return collected;
}

/**
 * Post a comment on a GitHub PR using the gh CLI.
 */
export function postComment(prNumber: number, body: string): void {
  try {
    execFileSync("gh", ["pr", "comment", String(prNumber), "--body", body], {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    console.log(pc.green(`✓ Comment posted to PR #${prNumber}`));
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(pc.red(`Failed to post PR comment: ${message}`));
    console.error(pc.dim("Ensure gh CLI is installed and GITHUB_TOKEN is set."));
    throw err;
  }
}
